#ifndef MINI_PP_VERSION // Allows this file to be included from anywhere
#include "MiniPP/MiniPP.hpp"
#include "TestUtility.hpp"
#endif

////////////////////////////////////////////////////////////
// Call With Args
// Should not be used any more but keep it here for tests
////////////////////////////////////////////////////////////

#define MINI_PP_CALL_WITH_ARGS(/*func,*/ ...) MINI_PP_EXPAND(MINI_PP_CAT_IS_MORE_THAN_1_ARGS(MINI_PP_PRIVATE_CALL_WITH_ARGS_IMPL_WITH_VA_ARGS_, __VA_ARGS__)(__VA_ARGS__))
#define MINI_PP_PRIVATE_CALL_WITH_ARGS_IMPL_WITH_VA_ARGS_0(func) MINI_PP_EXPAND(func())
#define MINI_PP_PRIVATE_CALL_WITH_ARGS_IMPL_WITH_VA_ARGS_1(func, ...) MINI_PP_EXPAND(func(__VA_ARGS__))

////////////////////////////////////////////////////////////

#define VALUE_4 4
#define VALUE_2 2
#define VALUE_42() 42
#define ARG_SEQ_4_2 4, 2
#define ARG_SEQ_4_2_CALL() 4, 2
#define GET_FIRST(a, b) a
#define GET_SECOND(a, b) b

///////////////// MINI_PP_CALL_WITH_ARGS /////////////////
static_assert(MINI_PP_CALL_WITH_ARGS(VALUE_42) == 42, "MINI_PP_CALL_WITH_ARGS is broken");
static_assert(MINI_PP_CALL_WITH_ARGS(GET_FIRST, 4, 2) == 4, "MINI_PP_CALL_WITH_ARGS is broken");
static_assert(MINI_PP_CALL_WITH_ARGS(GET_SECOND, 4, 2) == 2, "MINI_PP_CALL_WITH_ARGS is broken");
static_assert(MINI_PP_CALL_WITH_ARGS(GET_FIRST, VALUE_4, 2) == 4, "MINI_PP_CALL_WITH_ARGS is broken");
static_assert(MINI_PP_CALL_WITH_ARGS(GET_SECOND, VALUE_4, VALUE_2) == 2, "MINI_PP_CALL_WITH_ARGS is broken");
static_assert(MINI_PP_CALL_WITH_ARGS(GET_FIRST, ARG_SEQ_4_2) == 4, "MINI_PP_CALL_WITH_ARGS is broken");
static_assert(MINI_PP_CALL_WITH_ARGS(GET_SECOND, ARG_SEQ_4_2) == 2, "MINI_PP_CALL_WITH_ARGS is broken");
static_assert(MINI_PP_CAT(4, MINI_PP_CALL_WITH_ARGS(VALUE_42)) == 442, "MINI_PP_CALL_WITH_ARGS is broken");
static_assert(MINI_PP_CAT(4, MINI_PP_CALL_WITH_ARGS(GET_FIRST, 4, 2)) == 44, "MINI_PP_CALL_WITH_ARGS is broken");
static_assert(MINI_PP_CAT(4, MINI_PP_CALL_WITH_ARGS(GET_SECOND, 4, 2)) == 42, "MINI_PP_CALL_WITH_ARGS is broken");
static_assert(MINI_PP_CAT(4, MINI_PP_CALL_WITH_ARGS(GET_FIRST, VALUE_4, 2)) == 44, "MINI_PP_CALL_WITH_ARGS is broken");
static_assert(MINI_PP_CAT(4, MINI_PP_CALL_WITH_ARGS(GET_SECOND, VALUE_4, VALUE_2)) == 42, "MINI_PP_CALL_WITH_ARGS is broken");
static_assert(MINI_PP_CAT(4, MINI_PP_CALL_WITH_ARGS(GET_FIRST, ARG_SEQ_4_2)) == 44, "MINI_PP_CALL_WITH_ARGS is broken");
static_assert(MINI_PP_CAT(4, MINI_PP_CALL_WITH_ARGS(GET_SECOND, ARG_SEQ_4_2)) == 42, "MINI_PP_CALL_WITH_ARGS is broken");

///////////////// MINI_PP_CALL_WITH_ARGS + MINI_PP_TO_TEXT /////////////////
static_assert(stringsEqual(MINI_PP_CALL_WITH_ARGS(MINI_PP_TO_TEXT, VALUE_42()), "42"), "MINI_PP_CALL_WITH_ARGS + MINI_PP_TO_TEXT is broken");

///////////////// MINI_PP_CALL_WITH_ARGS + MINI_PP_TO_TEXT + MINI_PP_PARENS /////////////////
static_assert(stringsEqual(MINI_PP_CALL_WITH_ARGS(MINI_PP_TO_TEXT, VALUE_42 MINI_PP_PARENS), "42"), "MINI_PP_CALL_WITH_ARGS + MINI_PP_TO_TEXT + MINI_PP_PARENS is broken");

///////////////// MINI_PP_CALL_WITH_ARGS + MINI_PP_TO_TEXT + MINI_PP_CALL_WITH_ARGS /////////////////
static_assert(stringsEqual(MINI_PP_CALL_WITH_ARGS(MINI_PP_TO_TEXT, MINI_PP_CALL_WITH_ARGS(VALUE_42)), "42"), "MINI_PP_CALL_WITH_ARGS + MINI_PP_TO_TEXT + MINI_PP_CALL_WITH_ARGS is broken");

///////////////// MINI_PP_CALL_WITH_ARGS + MINI_PP_TO_TEXT + MINI_PP_TUPLE_EXPAND /////////////////
#define TO_TEXT_2(a, b) MINI_PP_TO_TEXT(a) ", " MINI_PP_TO_TEXT(b)
static_assert(stringsEqual(MINI_PP_CALL_WITH_ARGS(MINI_PP_TO_TEXT, MINI_PP_TUPLE_EXPAND((a))), "a"), "MINI_PP_CALL_WITH_ARGS + MINI_PP_TO_TEXT + MINI_PP_TUPLE_EXPAND is broken");
static_assert(stringsEqual(MINI_PP_CALL_WITH_ARGS(TO_TEXT_2, MINI_PP_TUPLE_EXPAND((ARG_SEQ_4_2))), "4, 2"), "MINI_PP_CALL_WITH_ARGS + MINI_PP_TO_TEXT + MINI_PP_TUPLE_EXPAND is broken");
static_assert(stringsEqual(MINI_PP_CALL_WITH_ARGS(TO_TEXT_2, MINI_PP_TUPLE_EXPAND((ARG_SEQ_4_2_CALL()))), "4, 2"), "MINI_PP_CALL_WITH_ARGS + MINI_PP_TO_TEXT + MINI_PP_TUPLE_EXPAND is broken");

///////////////// MINI_PP_CALL_WITH_ARGS + MINI_PP_TO_TEXT + MINI_PP_TUPLE_POP_FRONT /////////////////
static_assert(stringsEqual(MINI_PP_CALL_WITH_ARGS(MINI_PP_TO_TEXT, MINI_PP_TUPLE_POP_FRONT((1, 2))), "(2)"), "MINI_PP_CALL_WITH_ARGS + MINI_PP_TO_TEXT + MINI_PP_TUPLE_POP_FRONT is broken");
static_assert(stringsEqual(MINI_PP_CALL_WITH_ARGS(MINI_PP_TO_TEXT, MINI_PP_TUPLE_POP_FRONT((ARG_SEQ_4_2))), "(2)"), "MINI_PP_CALL_WITH_ARGS + MINI_PP_TO_TEXT + MINI_PP_TUPLE_POP_FRONT is broken");
static_assert(stringsEqual(MINI_PP_CALL_WITH_ARGS(MINI_PP_TO_TEXT, MINI_PP_TUPLE_POP_FRONT((ARG_SEQ_4_2_CALL()))), "(2)"), "MINI_PP_CALL_WITH_ARGS + MINI_PP_TO_TEXT + MINI_PP_TUPLE_POP_FRONT is broken");

///////////////// MINI_PP_CALL_WITH_ARGS + MINI_PP_TO_TEXT + MINI_PP_TUPLE_GET_ELEM_0 /////////////////
static_assert(stringsEqual(MINI_PP_CALL_WITH_ARGS(MINI_PP_TO_TEXT, MINI_PP_TUPLE_GET_ELEM_0((ARG_SEQ_4_2))), "4"), "MINI_PP_CALL_WITH_ARGS + MINI_PP_TO_TEXT + MINI_PP_TUPLE_GET_ELEM_0 is broken");
static_assert(stringsEqual(MINI_PP_CALL_WITH_ARGS(MINI_PP_TO_TEXT, MINI_PP_TUPLE_GET_ELEM_0((ARG_SEQ_4_2_CALL()))), "4"), "MINI_PP_CALL_WITH_ARGS + MINI_PP_TO_TEXT + MINI_PP_TUPLE_GET_ELEM_0 is broken");


#define WHILE(predicate, operation, params) WHILE_0(predicate, operation, params)
#define WHILE_STOP(predicate, operation, params)
#define WHILE_0(predicate, operation, params) MINI_PP_IF_ELSE(predicate(params), WHILE_1, params WHILE_STOP)(predicate, operation, MINI_PP_IF_ELSE(predicate(params), operation, MINI_PP_EXPAND)(params))
#define WHILE_1(predicate, operation, params) MINI_PP_IF_ELSE(predicate(params), WHILE_2, params WHILE_STOP)(predicate, operation, MINI_PP_IF_ELSE(predicate(params), operation, MINI_PP_EXPAND)(params))
#define WHILE_2(predicate, operation, params) MINI_PP_IF_ELSE(predicate(params), WHILE_3, params WHILE_STOP)(predicate, operation, MINI_PP_IF_ELSE(predicate(params), operation, MINI_PP_EXPAND)(params))
#define WHILE_3(predicate, operation, params) MINI_PP_IF_ELSE(predicate(params), WHILE_4, params WHILE_STOP)(predicate, operation, MINI_PP_IF_ELSE(predicate(params), operation, MINI_PP_EXPAND)(params))
#define WHILE_4(predicate, operation, params) MINI_PP_IF_ELSE(predicate(params), WHILE_5, params WHILE_STOP)(predicate, operation, MINI_PP_IF_ELSE(predicate(params), operation, MINI_PP_EXPAND)(params))
#define WHILE_5(predicate, operation, params) MINI_PP_IF_ELSE(predicate(params), WHILE_6, params WHILE_STOP)(predicate, operation, MINI_PP_IF_ELSE(predicate(params), operation, MINI_PP_EXPAND)(params))
#define WHILE_6(predicate, operation, params) MINI_PP_IF_ELSE(predicate(params), WHILE_7, params WHILE_STOP)(predicate, operation, MINI_PP_IF_ELSE(predicate(params), operation, MINI_PP_EXPAND)(params))
#define WHILE_7(predicate, operation, params) MINI_PP_IF_ELSE(predicate(params), WHILE_8, params WHILE_STOP)(predicate, operation, MINI_PP_IF_ELSE(predicate(params), operation, MINI_PP_EXPAND)(params))

#define MY_PRED(params) MINI_PP_NOT(MINI_PP_IS_EQUAL(0, MINI_PP_TUPLE_GET_ELEM_0(params)))
#define MY_OP(params) MINI_PP_MAKE_TUPLE(MINI_PP_DEC(MINI_PP_TUPLE_GET_ELEM_0(params)), MINI_PP_INC(MINI_PP_TUPLE_GET_ELEM_1(params)))

static_assert(MINI_PP_TUPLE_GET_ELEM_1(WHILE(MY_PRED, MY_OP, MINI_PP_MAKE_TUPLE(5, 19))) == 24, "");


#define FUNC(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, \
	_41, _42, _43, _44, _45, _46, _47, _48, _49, _50, _51, _52, _53, _54, _55, _56, _57, _58, _59, _60, _61, _62, _63, _64, _65, _66, _67, _68, _69, _70, _71, _72, _73, _74, _75, _76, _77, _78, _79, _80, _81, _82, _83, _84, _85, _86, _87, _88, _89, \
	_90, _91, _92, _93, _94, _95, _96, _97, _98, _99, _100, _101, _102, _103, _104, _105, _106, _107, _108, _109, _110, _111, _112, _113, _114, _115, _116, _117, _118, _119, _120, _121, _122, _123, _124, _125, ...)

FUNC(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, \
	 _41, _42, _43, _44, _45, _46, _47, _48, _49, _50, _51, _52, _53, _54, _55, _56, _57, _58, _59, _60, _61, _62, _63, _64, _65, _66, _67, _68, _69, _70, _71, _72, _73, _74, _75, _76, _77, _78, _79, _80, _81, _82, _83, _84, _85, _86, _87, _88, _89, \
	 _90, _91, _92, _93, _94, _95, _96, _97, _98, _99, _100, _101, _102, _103, _104, _105, _106, _107, _108, _109, _110, _111, _112, _113, _114, _115, _116, _117, _118, _119, _120, _121, _122, _123, _124, _125, _126, _127, _128, _129, _130, _131)

#define MINI_PP_SEQ_SIZE_0(...) MINI_PP_SEQ_SIZE_1
#define MINI_PP_SEQ_SIZE_1(...) MINI_PP_SEQ_SIZE_2
#define MINI_PP_SEQ_SIZE_2(...) MINI_PP_SEQ_SIZE_3
#define MINI_PP_SEQ_SIZE_3(...) MINI_PP_SEQ_SIZE_4
#define MINI_PP_SEQ_SIZE_4(...) MINI_PP_SEQ_SIZE_5
#define MINI_PP_SEQ_SIZE_5(...) MINI_PP_SEQ_SIZE_6
#define MINI_PP_SEQ_SIZE_6(...) MINI_PP_SEQ_SIZE_7
#define MINI_PP_SEQ_SIZE_7(...) MINI_PP_SEQ_SIZE_8
#define MINI_PP_SEQ_SIZE_8(...) MINI_PP_SEQ_SIZE_9
#define MINI_PP_SEQ_SIZE_9(...) MINI_PP_SEQ_SIZE_10
#define MINI_PP_SEQ_SIZE_10(...) MINI_PP_SEQ_SIZE_11
#define MINI_PP_SEQ_SIZE_11(...) MINI_PP_SEQ_SIZE_12
#define MINI_PP_SEQ_SIZE_12(...) MINI_PP_SEQ_SIZE_13
#define MINI_PP_SEQ_SIZE_13(...) MINI_PP_SEQ_SIZE_14
#define MINI_PP_SEQ_SIZE_14(...) MINI_PP_SEQ_SIZE_15
#define MINI_PP_SEQ_SIZE_15(...) MINI_PP_SEQ_SIZE_16
#define MINI_PP_SEQ_SIZE_16(...) MINI_PP_SEQ_SIZE_17
#define MINI_PP_SEQ_SIZE_17(...) MINI_PP_SEQ_SIZE_18
#define MINI_PP_SEQ_SIZE_18(...) MINI_PP_SEQ_SIZE_19
#define MINI_PP_SEQ_SIZE_19(...) MINI_PP_SEQ_SIZE_20
#define MINI_PP_SEQ_SIZE_20(...) MINI_PP_SEQ_SIZE_21
#define MINI_PP_SEQ_SIZE_21(...) MINI_PP_SEQ_SIZE_22
#define MINI_PP_SEQ_SIZE_22(...) MINI_PP_SEQ_SIZE_23
#define MINI_PP_SEQ_SIZE_23(...) MINI_PP_SEQ_SIZE_24
#define MINI_PP_SEQ_SIZE_24(...) MINI_PP_SEQ_SIZE_25
#define MINI_PP_SEQ_SIZE_25(...) MINI_PP_SEQ_SIZE_26
#define MINI_PP_SEQ_SIZE_26(...) MINI_PP_SEQ_SIZE_27
#define MINI_PP_SEQ_SIZE_27(...) MINI_PP_SEQ_SIZE_28
#define MINI_PP_SEQ_SIZE_28(...) MINI_PP_SEQ_SIZE_29
#define MINI_PP_SEQ_SIZE_29(...) MINI_PP_SEQ_SIZE_30
#define MINI_PP_SEQ_SIZE_30(...) MINI_PP_SEQ_SIZE_31
#define MINI_PP_SEQ_SIZE_31(...) MINI_PP_SEQ_SIZE_32
#define MINI_PP_SEQ_SIZE_32(...) MINI_PP_SEQ_SIZE_33
#define MINI_PP_SEQ_SIZE_33(...) MINI_PP_SEQ_SIZE_34
#define MINI_PP_SEQ_SIZE_34(...) MINI_PP_SEQ_SIZE_35
#define MINI_PP_SEQ_SIZE_35(...) MINI_PP_SEQ_SIZE_36
#define MINI_PP_SEQ_SIZE_36(...) MINI_PP_SEQ_SIZE_37
#define MINI_PP_SEQ_SIZE_37(...) MINI_PP_SEQ_SIZE_38
#define MINI_PP_SEQ_SIZE_38(...) MINI_PP_SEQ_SIZE_39
#define MINI_PP_SEQ_SIZE_39(...) MINI_PP_SEQ_SIZE_40
#define MINI_PP_SEQ_SIZE_40(...) MINI_PP_SEQ_SIZE_41
#define MINI_PP_SEQ_SIZE_41(...) MINI_PP_SEQ_SIZE_42
#define MINI_PP_SEQ_SIZE_42(...) MINI_PP_SEQ_SIZE_43
#define MINI_PP_SEQ_SIZE_43(...) MINI_PP_SEQ_SIZE_44
#define MINI_PP_SEQ_SIZE_44(...) MINI_PP_SEQ_SIZE_45
#define MINI_PP_SEQ_SIZE_45(...) MINI_PP_SEQ_SIZE_46
#define MINI_PP_SEQ_SIZE_46(...) MINI_PP_SEQ_SIZE_47
#define MINI_PP_SEQ_SIZE_47(...) MINI_PP_SEQ_SIZE_48
#define MINI_PP_SEQ_SIZE_48(...) MINI_PP_SEQ_SIZE_49
#define MINI_PP_SEQ_SIZE_49(...) MINI_PP_SEQ_SIZE_50
#define MINI_PP_SEQ_SIZE_50(...) MINI_PP_SEQ_SIZE_51
#define MINI_PP_SEQ_SIZE_51(...) MINI_PP_SEQ_SIZE_52
#define MINI_PP_SEQ_SIZE_52(...) MINI_PP_SEQ_SIZE_53
#define MINI_PP_SEQ_SIZE_53(...) MINI_PP_SEQ_SIZE_54
#define MINI_PP_SEQ_SIZE_54(...) MINI_PP_SEQ_SIZE_55
#define MINI_PP_SEQ_SIZE_55(...) MINI_PP_SEQ_SIZE_56
#define MINI_PP_SEQ_SIZE_56(...) MINI_PP_SEQ_SIZE_57
#define MINI_PP_SEQ_SIZE_57(...) MINI_PP_SEQ_SIZE_58
#define MINI_PP_SEQ_SIZE_58(...) MINI_PP_SEQ_SIZE_59
#define MINI_PP_SEQ_SIZE_59(...) MINI_PP_SEQ_SIZE_60
#define MINI_PP_SEQ_SIZE_60(...) MINI_PP_SEQ_SIZE_61
#define MINI_PP_SEQ_SIZE_61(...) MINI_PP_SEQ_SIZE_62
#define MINI_PP_SEQ_SIZE_62(...) MINI_PP_SEQ_SIZE_63
#define MINI_PP_SEQ_SIZE_63(...) MINI_PP_SEQ_SIZE_64
#define MINI_PP_SEQ_SIZE_64(...) MINI_PP_SEQ_SIZE_65
#define MINI_PP_SEQ_SIZE_65(...) MINI_PP_SEQ_SIZE_66
#define MINI_PP_SEQ_SIZE_66(...) MINI_PP_SEQ_SIZE_67
#define MINI_PP_SEQ_SIZE_67(...) MINI_PP_SEQ_SIZE_68
#define MINI_PP_SEQ_SIZE_68(...) MINI_PP_SEQ_SIZE_69
#define MINI_PP_SEQ_SIZE_69(...) MINI_PP_SEQ_SIZE_70
#define MINI_PP_SEQ_SIZE_70(...) MINI_PP_SEQ_SIZE_71
#define MINI_PP_SEQ_SIZE_71(...) MINI_PP_SEQ_SIZE_72
#define MINI_PP_SEQ_SIZE_72(...) MINI_PP_SEQ_SIZE_73
#define MINI_PP_SEQ_SIZE_73(...) MINI_PP_SEQ_SIZE_74
#define MINI_PP_SEQ_SIZE_74(...) MINI_PP_SEQ_SIZE_75
#define MINI_PP_SEQ_SIZE_75(...) MINI_PP_SEQ_SIZE_76
#define MINI_PP_SEQ_SIZE_76(...) MINI_PP_SEQ_SIZE_77
#define MINI_PP_SEQ_SIZE_77(...) MINI_PP_SEQ_SIZE_78
#define MINI_PP_SEQ_SIZE_78(...) MINI_PP_SEQ_SIZE_79
#define MINI_PP_SEQ_SIZE_79(...) MINI_PP_SEQ_SIZE_80
#define MINI_PP_SEQ_SIZE_80(...) MINI_PP_SEQ_SIZE_81
#define MINI_PP_SEQ_SIZE_81(...) MINI_PP_SEQ_SIZE_82
#define MINI_PP_SEQ_SIZE_82(...) MINI_PP_SEQ_SIZE_83
#define MINI_PP_SEQ_SIZE_83(...) MINI_PP_SEQ_SIZE_84
#define MINI_PP_SEQ_SIZE_84(...) MINI_PP_SEQ_SIZE_85
#define MINI_PP_SEQ_SIZE_85(...) MINI_PP_SEQ_SIZE_86
#define MINI_PP_SEQ_SIZE_86(...) MINI_PP_SEQ_SIZE_87
#define MINI_PP_SEQ_SIZE_87(...) MINI_PP_SEQ_SIZE_88
#define MINI_PP_SEQ_SIZE_88(...) MINI_PP_SEQ_SIZE_89
#define MINI_PP_SEQ_SIZE_89(...) MINI_PP_SEQ_SIZE_90
#define MINI_PP_SEQ_SIZE_90(...) MINI_PP_SEQ_SIZE_91
#define MINI_PP_SEQ_SIZE_91(...) MINI_PP_SEQ_SIZE_92
#define MINI_PP_SEQ_SIZE_92(...) MINI_PP_SEQ_SIZE_93
#define MINI_PP_SEQ_SIZE_93(...) MINI_PP_SEQ_SIZE_94
#define MINI_PP_SEQ_SIZE_94(...) MINI_PP_SEQ_SIZE_95
#define MINI_PP_SEQ_SIZE_95(...) MINI_PP_SEQ_SIZE_96
#define MINI_PP_SEQ_SIZE_96(...) MINI_PP_SEQ_SIZE_97
#define MINI_PP_SEQ_SIZE_97(...) MINI_PP_SEQ_SIZE_98
#define MINI_PP_SEQ_SIZE_98(...) MINI_PP_SEQ_SIZE_99
#define MINI_PP_SEQ_SIZE_99(...) MINI_PP_SEQ_SIZE_100
#define MINI_PP_SEQ_SIZE_100(...) MINI_PP_SEQ_SIZE_101
#define MINI_PP_SEQ_SIZE_101(...) MINI_PP_SEQ_SIZE_102
#define MINI_PP_SEQ_SIZE_102(...) MINI_PP_SEQ_SIZE_103
#define MINI_PP_SEQ_SIZE_103(...) MINI_PP_SEQ_SIZE_104
#define MINI_PP_SEQ_SIZE_104(...) MINI_PP_SEQ_SIZE_105
#define MINI_PP_SEQ_SIZE_105(...) MINI_PP_SEQ_SIZE_106
#define MINI_PP_SEQ_SIZE_106(...) MINI_PP_SEQ_SIZE_107
#define MINI_PP_SEQ_SIZE_107(...) MINI_PP_SEQ_SIZE_108
#define MINI_PP_SEQ_SIZE_108(...) MINI_PP_SEQ_SIZE_109
#define MINI_PP_SEQ_SIZE_109(...) MINI_PP_SEQ_SIZE_110
#define MINI_PP_SEQ_SIZE_110(...) MINI_PP_SEQ_SIZE_111
#define MINI_PP_SEQ_SIZE_111(...) MINI_PP_SEQ_SIZE_112
#define MINI_PP_SEQ_SIZE_112(...) MINI_PP_SEQ_SIZE_113
#define MINI_PP_SEQ_SIZE_113(...) MINI_PP_SEQ_SIZE_114
#define MINI_PP_SEQ_SIZE_114(...) MINI_PP_SEQ_SIZE_115
#define MINI_PP_SEQ_SIZE_115(...) MINI_PP_SEQ_SIZE_116
#define MINI_PP_SEQ_SIZE_116(...) MINI_PP_SEQ_SIZE_117
#define MINI_PP_SEQ_SIZE_117(...) MINI_PP_SEQ_SIZE_118
#define MINI_PP_SEQ_SIZE_118(...) MINI_PP_SEQ_SIZE_119
#define MINI_PP_SEQ_SIZE_119(...) MINI_PP_SEQ_SIZE_120
#define MINI_PP_SEQ_SIZE_120(...) MINI_PP_SEQ_SIZE_121
#define MINI_PP_SEQ_SIZE_121(...) MINI_PP_SEQ_SIZE_122
#define MINI_PP_SEQ_SIZE_122(...) MINI_PP_SEQ_SIZE_123
#define MINI_PP_SEQ_SIZE_123(...) MINI_PP_SEQ_SIZE_124
#define MINI_PP_SEQ_SIZE_124(...) MINI_PP_SEQ_SIZE_125
#define MINI_PP_SEQ_SIZE_125(...) MINI_PP_SEQ_SIZE_126
#define MINI_PP_SEQ_SIZE_126(...) MINI_PP_SEQ_SIZE_127
#define MINI_PP_SEQ_SIZE_127(...) MINI_PP_SEQ_SIZE_128
#define MINI_PP_SEQ_SIZE_128(...) MINI_PP_SEQ_SIZE_129
#define MINI_PP_SEQ_SIZE_129(...) MINI_PP_SEQ_SIZE_130
#define MINI_PP_SEQ_SIZE_130(...) MINI_PP_SEQ_SIZE_131
#define MINI_PP_SEQ_SIZE_131(...) MINI_PP_SEQ_SIZE_132
#define MINI_PP_SEQ_SIZE_132(...) MINI_PP_SEQ_SIZE_133
#define MINI_PP_SEQ_SIZE_133(...) MINI_PP_SEQ_SIZE_134
#define MINI_PP_SEQ_SIZE_134(...) MINI_PP_SEQ_SIZE_135
#define MINI_PP_SEQ_SIZE_135(...) MINI_PP_SEQ_SIZE_136
#define MINI_PP_SEQ_SIZE_136(...) MINI_PP_SEQ_SIZE_137
#define MINI_PP_SEQ_SIZE_137(...) MINI_PP_SEQ_SIZE_138
#define MINI_PP_SEQ_SIZE_138(...) MINI_PP_SEQ_SIZE_139
#define MINI_PP_SEQ_SIZE_139(...) MINI_PP_SEQ_SIZE_140
#define MINI_PP_SEQ_SIZE_140(...) MINI_PP_SEQ_SIZE_141
#define MINI_PP_SEQ_SIZE_141(...) MINI_PP_SEQ_SIZE_142
#define MINI_PP_SEQ_SIZE_142(...) MINI_PP_SEQ_SIZE_143
#define MINI_PP_SEQ_SIZE_143(...) MINI_PP_SEQ_SIZE_144
#define MINI_PP_SEQ_SIZE_144(...) MINI_PP_SEQ_SIZE_145
#define MINI_PP_SEQ_SIZE_145(...) MINI_PP_SEQ_SIZE_146
#define MINI_PP_SEQ_SIZE_146(...) MINI_PP_SEQ_SIZE_147
#define MINI_PP_SEQ_SIZE_147(...) MINI_PP_SEQ_SIZE_148
#define MINI_PP_SEQ_SIZE_148(...) MINI_PP_SEQ_SIZE_149
#define MINI_PP_SEQ_SIZE_149(...) MINI_PP_SEQ_SIZE_150
#define MINI_PP_SEQ_SIZE_150(...) MINI_PP_SEQ_SIZE_151
#define MINI_PP_SEQ_SIZE_151(...) MINI_PP_SEQ_SIZE_152
#define MINI_PP_SEQ_SIZE_152(...) MINI_PP_SEQ_SIZE_153
#define MINI_PP_SEQ_SIZE_153(...) MINI_PP_SEQ_SIZE_154
#define MINI_PP_SEQ_SIZE_154(...) MINI_PP_SEQ_SIZE_155
#define MINI_PP_SEQ_SIZE_155(...) MINI_PP_SEQ_SIZE_156
#define MINI_PP_SEQ_SIZE_156(...) MINI_PP_SEQ_SIZE_157
#define MINI_PP_SEQ_SIZE_157(...) MINI_PP_SEQ_SIZE_158
#define MINI_PP_SEQ_SIZE_158(...) MINI_PP_SEQ_SIZE_159
#define MINI_PP_SEQ_SIZE_159(...) MINI_PP_SEQ_SIZE_160
#define MINI_PP_SEQ_SIZE_160(...) MINI_PP_SEQ_SIZE_161
#define MINI_PP_SEQ_SIZE_161(...) MINI_PP_SEQ_SIZE_162
#define MINI_PP_SEQ_SIZE_162(...) MINI_PP_SEQ_SIZE_163
#define MINI_PP_SEQ_SIZE_163(...) MINI_PP_SEQ_SIZE_164
#define MINI_PP_SEQ_SIZE_164(...) MINI_PP_SEQ_SIZE_165
#define MINI_PP_SEQ_SIZE_165(...) MINI_PP_SEQ_SIZE_166
#define MINI_PP_SEQ_SIZE_166(...) MINI_PP_SEQ_SIZE_167
#define MINI_PP_SEQ_SIZE_167(...) MINI_PP_SEQ_SIZE_168
#define MINI_PP_SEQ_SIZE_168(...) MINI_PP_SEQ_SIZE_169
#define MINI_PP_SEQ_SIZE_169(...) MINI_PP_SEQ_SIZE_170
#define MINI_PP_SEQ_SIZE_170(...) MINI_PP_SEQ_SIZE_171
#define MINI_PP_SEQ_SIZE_171(...) MINI_PP_SEQ_SIZE_172
#define MINI_PP_SEQ_SIZE_172(...) MINI_PP_SEQ_SIZE_173
#define MINI_PP_SEQ_SIZE_173(...) MINI_PP_SEQ_SIZE_174
#define MINI_PP_SEQ_SIZE_174(...) MINI_PP_SEQ_SIZE_175
#define MINI_PP_SEQ_SIZE_175(...) MINI_PP_SEQ_SIZE_176
#define MINI_PP_SEQ_SIZE_176(...) MINI_PP_SEQ_SIZE_177
#define MINI_PP_SEQ_SIZE_177(...) MINI_PP_SEQ_SIZE_178
#define MINI_PP_SEQ_SIZE_178(...) MINI_PP_SEQ_SIZE_179
#define MINI_PP_SEQ_SIZE_179(...) MINI_PP_SEQ_SIZE_180
#define MINI_PP_SEQ_SIZE_180(...) MINI_PP_SEQ_SIZE_181
#define MINI_PP_SEQ_SIZE_181(...) MINI_PP_SEQ_SIZE_182
#define MINI_PP_SEQ_SIZE_182(...) MINI_PP_SEQ_SIZE_183
#define MINI_PP_SEQ_SIZE_183(...) MINI_PP_SEQ_SIZE_184
#define MINI_PP_SEQ_SIZE_184(...) MINI_PP_SEQ_SIZE_185
#define MINI_PP_SEQ_SIZE_185(...) MINI_PP_SEQ_SIZE_186
#define MINI_PP_SEQ_SIZE_186(...) MINI_PP_SEQ_SIZE_187
#define MINI_PP_SEQ_SIZE_187(...) MINI_PP_SEQ_SIZE_188
#define MINI_PP_SEQ_SIZE_188(...) MINI_PP_SEQ_SIZE_189
#define MINI_PP_SEQ_SIZE_189(...) MINI_PP_SEQ_SIZE_190
#define MINI_PP_SEQ_SIZE_190(...) MINI_PP_SEQ_SIZE_191
#define MINI_PP_SEQ_SIZE_191(...) MINI_PP_SEQ_SIZE_192
#define MINI_PP_SEQ_SIZE_192(...) MINI_PP_SEQ_SIZE_193
#define MINI_PP_SEQ_SIZE_193(...) MINI_PP_SEQ_SIZE_194
#define MINI_PP_SEQ_SIZE_194(...) MINI_PP_SEQ_SIZE_195
#define MINI_PP_SEQ_SIZE_195(...) MINI_PP_SEQ_SIZE_196
#define MINI_PP_SEQ_SIZE_196(...) MINI_PP_SEQ_SIZE_197
#define MINI_PP_SEQ_SIZE_197(...) MINI_PP_SEQ_SIZE_198
#define MINI_PP_SEQ_SIZE_198(...) MINI_PP_SEQ_SIZE_199
#define MINI_PP_SEQ_SIZE_199(...) MINI_PP_SEQ_SIZE_200
#define MINI_PP_SEQ_SIZE_200(...) MINI_PP_SEQ_SIZE_201
#define MINI_PP_SEQ_SIZE_201(...) MINI_PP_SEQ_SIZE_202
#define MINI_PP_SEQ_SIZE_202(...) MINI_PP_SEQ_SIZE_203
#define MINI_PP_SEQ_SIZE_203(...) MINI_PP_SEQ_SIZE_204
#define MINI_PP_SEQ_SIZE_204(...) MINI_PP_SEQ_SIZE_205
#define MINI_PP_SEQ_SIZE_205(...) MINI_PP_SEQ_SIZE_206
#define MINI_PP_SEQ_SIZE_206(...) MINI_PP_SEQ_SIZE_207
#define MINI_PP_SEQ_SIZE_207(...) MINI_PP_SEQ_SIZE_208
#define MINI_PP_SEQ_SIZE_208(...) MINI_PP_SEQ_SIZE_209
#define MINI_PP_SEQ_SIZE_209(...) MINI_PP_SEQ_SIZE_210
#define MINI_PP_SEQ_SIZE_210(...) MINI_PP_SEQ_SIZE_211
#define MINI_PP_SEQ_SIZE_211(...) MINI_PP_SEQ_SIZE_212
#define MINI_PP_SEQ_SIZE_212(...) MINI_PP_SEQ_SIZE_213
#define MINI_PP_SEQ_SIZE_213(...) MINI_PP_SEQ_SIZE_214
#define MINI_PP_SEQ_SIZE_214(...) MINI_PP_SEQ_SIZE_215
#define MINI_PP_SEQ_SIZE_215(...) MINI_PP_SEQ_SIZE_216
#define MINI_PP_SEQ_SIZE_216(...) MINI_PP_SEQ_SIZE_217
#define MINI_PP_SEQ_SIZE_217(...) MINI_PP_SEQ_SIZE_218
#define MINI_PP_SEQ_SIZE_218(...) MINI_PP_SEQ_SIZE_219
#define MINI_PP_SEQ_SIZE_219(...) MINI_PP_SEQ_SIZE_220
#define MINI_PP_SEQ_SIZE_220(...) MINI_PP_SEQ_SIZE_221
#define MINI_PP_SEQ_SIZE_221(...) MINI_PP_SEQ_SIZE_222
#define MINI_PP_SEQ_SIZE_222(...) MINI_PP_SEQ_SIZE_223
#define MINI_PP_SEQ_SIZE_223(...) MINI_PP_SEQ_SIZE_224
#define MINI_PP_SEQ_SIZE_224(...) MINI_PP_SEQ_SIZE_225
#define MINI_PP_SEQ_SIZE_225(...) MINI_PP_SEQ_SIZE_226
#define MINI_PP_SEQ_SIZE_226(...) MINI_PP_SEQ_SIZE_227
#define MINI_PP_SEQ_SIZE_227(...) MINI_PP_SEQ_SIZE_228
#define MINI_PP_SEQ_SIZE_228(...) MINI_PP_SEQ_SIZE_229
#define MINI_PP_SEQ_SIZE_229(...) MINI_PP_SEQ_SIZE_230
#define MINI_PP_SEQ_SIZE_230(...) MINI_PP_SEQ_SIZE_231
#define MINI_PP_SEQ_SIZE_231(...) MINI_PP_SEQ_SIZE_232
#define MINI_PP_SEQ_SIZE_232(...) MINI_PP_SEQ_SIZE_233
#define MINI_PP_SEQ_SIZE_233(...) MINI_PP_SEQ_SIZE_234
#define MINI_PP_SEQ_SIZE_234(...) MINI_PP_SEQ_SIZE_235
#define MINI_PP_SEQ_SIZE_235(...) MINI_PP_SEQ_SIZE_236
#define MINI_PP_SEQ_SIZE_236(...) MINI_PP_SEQ_SIZE_237
#define MINI_PP_SEQ_SIZE_237(...) MINI_PP_SEQ_SIZE_238
#define MINI_PP_SEQ_SIZE_238(...) MINI_PP_SEQ_SIZE_239
#define MINI_PP_SEQ_SIZE_239(...) MINI_PP_SEQ_SIZE_240
#define MINI_PP_SEQ_SIZE_240(...) MINI_PP_SEQ_SIZE_241
#define MINI_PP_SEQ_SIZE_241(...) MINI_PP_SEQ_SIZE_242
#define MINI_PP_SEQ_SIZE_242(...) MINI_PP_SEQ_SIZE_243
#define MINI_PP_SEQ_SIZE_243(...) MINI_PP_SEQ_SIZE_244
#define MINI_PP_SEQ_SIZE_244(...) MINI_PP_SEQ_SIZE_245
#define MINI_PP_SEQ_SIZE_245(...) MINI_PP_SEQ_SIZE_246
#define MINI_PP_SEQ_SIZE_246(...) MINI_PP_SEQ_SIZE_247
#define MINI_PP_SEQ_SIZE_247(...) MINI_PP_SEQ_SIZE_248
#define MINI_PP_SEQ_SIZE_248(...) MINI_PP_SEQ_SIZE_249
#define MINI_PP_SEQ_SIZE_249(...) MINI_PP_SEQ_SIZE_250
#define MINI_PP_SEQ_SIZE_250(...) MINI_PP_SEQ_SIZE_251
#define MINI_PP_SEQ_SIZE_251(...) MINI_PP_SEQ_SIZE_252
#define MINI_PP_SEQ_SIZE_252(...) MINI_PP_SEQ_SIZE_253
#define MINI_PP_SEQ_SIZE_253(...) MINI_PP_SEQ_SIZE_254
#define MINI_PP_SEQ_SIZE_254(...) MINI_PP_SEQ_SIZE_255
#define MINI_PP_SEQ_SIZE_255(...) MINI_PP_SEQ_SIZE_256
#define MINI_PP_SEQ_SIZE_256(...) MINI_PP_SEQ_SIZE_257
#define MINI_PP_SEQ_SIZE_257(...) MINI_PP_SEQ_SIZE_258
#define MINI_PP_SEQ_SIZE_258(...) MINI_PP_SEQ_SIZE_259
#define MINI_PP_SEQ_SIZE_259(...) MINI_PP_SEQ_SIZE_260
#define MINI_PP_SEQ_SIZE_260(...) MINI_PP_SEQ_SIZE_261
#define MINI_PP_SEQ_SIZE_261(...) MINI_PP_SEQ_SIZE_262
#define MINI_PP_SEQ_SIZE_262(...) MINI_PP_SEQ_SIZE_263
#define MINI_PP_SEQ_SIZE_263(...) MINI_PP_SEQ_SIZE_264
#define MINI_PP_SEQ_SIZE_264(...) MINI_PP_SEQ_SIZE_265
#define MINI_PP_SEQ_SIZE_265(...) MINI_PP_SEQ_SIZE_266
#define MINI_PP_SEQ_SIZE_266(...) MINI_PP_SEQ_SIZE_267
#define MINI_PP_SEQ_SIZE_267(...) MINI_PP_SEQ_SIZE_268
#define MINI_PP_SEQ_SIZE_268(...) MINI_PP_SEQ_SIZE_269
#define MINI_PP_SEQ_SIZE_269(...) MINI_PP_SEQ_SIZE_270
#define MINI_PP_SEQ_SIZE_270(...) MINI_PP_SEQ_SIZE_271
#define MINI_PP_SEQ_SIZE_271(...) MINI_PP_SEQ_SIZE_272
#define MINI_PP_SEQ_SIZE_272(...) MINI_PP_SEQ_SIZE_273
#define MINI_PP_SEQ_SIZE_273(...) MINI_PP_SEQ_SIZE_274
#define MINI_PP_SEQ_SIZE_274(...) MINI_PP_SEQ_SIZE_275
#define MINI_PP_SEQ_SIZE_275(...) MINI_PP_SEQ_SIZE_276
#define MINI_PP_SEQ_SIZE_276(...) MINI_PP_SEQ_SIZE_277
#define MINI_PP_SEQ_SIZE_277(...) MINI_PP_SEQ_SIZE_278
#define MINI_PP_SEQ_SIZE_278(...) MINI_PP_SEQ_SIZE_279
#define MINI_PP_SEQ_SIZE_279(...) MINI_PP_SEQ_SIZE_280
#define MINI_PP_SEQ_SIZE_280(...) MINI_PP_SEQ_SIZE_281
#define MINI_PP_SEQ_SIZE_281(...) MINI_PP_SEQ_SIZE_282
#define MINI_PP_SEQ_SIZE_282(...) MINI_PP_SEQ_SIZE_283
#define MINI_PP_SEQ_SIZE_283(...) MINI_PP_SEQ_SIZE_284
#define MINI_PP_SEQ_SIZE_284(...) MINI_PP_SEQ_SIZE_285
#define MINI_PP_SEQ_SIZE_285(...) MINI_PP_SEQ_SIZE_286
#define MINI_PP_SEQ_SIZE_286(...) MINI_PP_SEQ_SIZE_287
#define MINI_PP_SEQ_SIZE_287(...) MINI_PP_SEQ_SIZE_288
#define MINI_PP_SEQ_SIZE_288(...) MINI_PP_SEQ_SIZE_289
#define MINI_PP_SEQ_SIZE_289(...) MINI_PP_SEQ_SIZE_290
#define MINI_PP_SEQ_SIZE_290(...) MINI_PP_SEQ_SIZE_291
#define MINI_PP_SEQ_SIZE_291(...) MINI_PP_SEQ_SIZE_292
#define MINI_PP_SEQ_SIZE_292(...) MINI_PP_SEQ_SIZE_293
#define MINI_PP_SEQ_SIZE_293(...) MINI_PP_SEQ_SIZE_294
#define MINI_PP_SEQ_SIZE_294(...) MINI_PP_SEQ_SIZE_295
#define MINI_PP_SEQ_SIZE_295(...) MINI_PP_SEQ_SIZE_296
#define MINI_PP_SEQ_SIZE_296(...) MINI_PP_SEQ_SIZE_297
#define MINI_PP_SEQ_SIZE_297(...) MINI_PP_SEQ_SIZE_298
#define MINI_PP_SEQ_SIZE_298(...) MINI_PP_SEQ_SIZE_299
#define MINI_PP_SEQ_SIZE_299(...) MINI_PP_SEQ_SIZE_300
#define MINI_PP_SEQ_SIZE_300(...) MINI_PP_SEQ_SIZE_301
#define MINI_PP_SEQ_SIZE_301(...) MINI_PP_SEQ_SIZE_302
#define MINI_PP_SEQ_SIZE_302(...) MINI_PP_SEQ_SIZE_303
#define MINI_PP_SEQ_SIZE_303(...) MINI_PP_SEQ_SIZE_304
#define MINI_PP_SEQ_SIZE_304(...) MINI_PP_SEQ_SIZE_305
#define MINI_PP_SEQ_SIZE_305(...) MINI_PP_SEQ_SIZE_306
#define MINI_PP_SEQ_SIZE_306(...) MINI_PP_SEQ_SIZE_307
#define MINI_PP_SEQ_SIZE_307(...) MINI_PP_SEQ_SIZE_308
#define MINI_PP_SEQ_SIZE_308(...) MINI_PP_SEQ_SIZE_309
#define MINI_PP_SEQ_SIZE_309(...) MINI_PP_SEQ_SIZE_310
#define MINI_PP_SEQ_SIZE_310(...) MINI_PP_SEQ_SIZE_311
#define MINI_PP_SEQ_SIZE_311(...) MINI_PP_SEQ_SIZE_312
#define MINI_PP_SEQ_SIZE_312(...) MINI_PP_SEQ_SIZE_313
#define MINI_PP_SEQ_SIZE_313(...) MINI_PP_SEQ_SIZE_314
#define MINI_PP_SEQ_SIZE_314(...) MINI_PP_SEQ_SIZE_315
#define MINI_PP_SEQ_SIZE_315(...) MINI_PP_SEQ_SIZE_316
#define MINI_PP_SEQ_SIZE_316(...) MINI_PP_SEQ_SIZE_317
#define MINI_PP_SEQ_SIZE_317(...) MINI_PP_SEQ_SIZE_318
#define MINI_PP_SEQ_SIZE_318(...) MINI_PP_SEQ_SIZE_319
#define MINI_PP_SEQ_SIZE_319(...) MINI_PP_SEQ_SIZE_320
#define MINI_PP_SEQ_SIZE_320(...) MINI_PP_SEQ_SIZE_321
#define MINI_PP_SEQ_SIZE_321(...) MINI_PP_SEQ_SIZE_322
#define MINI_PP_SEQ_SIZE_322(...) MINI_PP_SEQ_SIZE_323
#define MINI_PP_SEQ_SIZE_323(...) MINI_PP_SEQ_SIZE_324
#define MINI_PP_SEQ_SIZE_324(...) MINI_PP_SEQ_SIZE_325
#define MINI_PP_SEQ_SIZE_325(...) MINI_PP_SEQ_SIZE_326
#define MINI_PP_SEQ_SIZE_326(...) MINI_PP_SEQ_SIZE_327
#define MINI_PP_SEQ_SIZE_327(...) MINI_PP_SEQ_SIZE_328
#define MINI_PP_SEQ_SIZE_328(...) MINI_PP_SEQ_SIZE_329
#define MINI_PP_SEQ_SIZE_329(...) MINI_PP_SEQ_SIZE_330
#define MINI_PP_SEQ_SIZE_330(...) MINI_PP_SEQ_SIZE_331
#define MINI_PP_SEQ_SIZE_331(...) MINI_PP_SEQ_SIZE_332
#define MINI_PP_SEQ_SIZE_332(...) MINI_PP_SEQ_SIZE_333
#define MINI_PP_SEQ_SIZE_333(...) MINI_PP_SEQ_SIZE_334
#define MINI_PP_SEQ_SIZE_334(...) MINI_PP_SEQ_SIZE_335
#define MINI_PP_SEQ_SIZE_335(...) MINI_PP_SEQ_SIZE_336
#define MINI_PP_SEQ_SIZE_336(...) MINI_PP_SEQ_SIZE_337
#define MINI_PP_SEQ_SIZE_337(...) MINI_PP_SEQ_SIZE_338
#define MINI_PP_SEQ_SIZE_338(...) MINI_PP_SEQ_SIZE_339
#define MINI_PP_SEQ_SIZE_339(...) MINI_PP_SEQ_SIZE_340
#define MINI_PP_SEQ_SIZE_340(...) MINI_PP_SEQ_SIZE_341
#define MINI_PP_SEQ_SIZE_341(...) MINI_PP_SEQ_SIZE_342
#define MINI_PP_SEQ_SIZE_342(...) MINI_PP_SEQ_SIZE_343
#define MINI_PP_SEQ_SIZE_343(...) MINI_PP_SEQ_SIZE_344
#define MINI_PP_SEQ_SIZE_344(...) MINI_PP_SEQ_SIZE_345
#define MINI_PP_SEQ_SIZE_345(...) MINI_PP_SEQ_SIZE_346
#define MINI_PP_SEQ_SIZE_346(...) MINI_PP_SEQ_SIZE_347
#define MINI_PP_SEQ_SIZE_347(...) MINI_PP_SEQ_SIZE_348
#define MINI_PP_SEQ_SIZE_348(...) MINI_PP_SEQ_SIZE_349
#define MINI_PP_SEQ_SIZE_349(...) MINI_PP_SEQ_SIZE_350
#define MINI_PP_SEQ_SIZE_350(...) MINI_PP_SEQ_SIZE_351
#define MINI_PP_SEQ_SIZE_351(...) MINI_PP_SEQ_SIZE_352
#define MINI_PP_SEQ_SIZE_352(...) MINI_PP_SEQ_SIZE_353
#define MINI_PP_SEQ_SIZE_353(...) MINI_PP_SEQ_SIZE_354
#define MINI_PP_SEQ_SIZE_354(...) MINI_PP_SEQ_SIZE_355
#define MINI_PP_SEQ_SIZE_355(...) MINI_PP_SEQ_SIZE_356
#define MINI_PP_SEQ_SIZE_356(...) MINI_PP_SEQ_SIZE_357
#define MINI_PP_SEQ_SIZE_357(...) MINI_PP_SEQ_SIZE_358
#define MINI_PP_SEQ_SIZE_358(...) MINI_PP_SEQ_SIZE_359
#define MINI_PP_SEQ_SIZE_359(...) MINI_PP_SEQ_SIZE_360
#define MINI_PP_SEQ_SIZE_360(...) MINI_PP_SEQ_SIZE_361
#define MINI_PP_SEQ_SIZE_361(...) MINI_PP_SEQ_SIZE_362
#define MINI_PP_SEQ_SIZE_362(...) MINI_PP_SEQ_SIZE_363
#define MINI_PP_SEQ_SIZE_363(...) MINI_PP_SEQ_SIZE_364
#define MINI_PP_SEQ_SIZE_364(...) MINI_PP_SEQ_SIZE_365
#define MINI_PP_SEQ_SIZE_365(...) MINI_PP_SEQ_SIZE_366
#define MINI_PP_SEQ_SIZE_366(...) MINI_PP_SEQ_SIZE_367
#define MINI_PP_SEQ_SIZE_367(...) MINI_PP_SEQ_SIZE_368
#define MINI_PP_SEQ_SIZE_368(...) MINI_PP_SEQ_SIZE_369
#define MINI_PP_SEQ_SIZE_369(...) MINI_PP_SEQ_SIZE_370
#define MINI_PP_SEQ_SIZE_370(...) MINI_PP_SEQ_SIZE_371
#define MINI_PP_SEQ_SIZE_371(...) MINI_PP_SEQ_SIZE_372
#define MINI_PP_SEQ_SIZE_372(...) MINI_PP_SEQ_SIZE_373
#define MINI_PP_SEQ_SIZE_373(...) MINI_PP_SEQ_SIZE_374
#define MINI_PP_SEQ_SIZE_374(...) MINI_PP_SEQ_SIZE_375
#define MINI_PP_SEQ_SIZE_375(...) MINI_PP_SEQ_SIZE_376
#define MINI_PP_SEQ_SIZE_376(...) MINI_PP_SEQ_SIZE_377
#define MINI_PP_SEQ_SIZE_377(...) MINI_PP_SEQ_SIZE_378
#define MINI_PP_SEQ_SIZE_378(...) MINI_PP_SEQ_SIZE_379
#define MINI_PP_SEQ_SIZE_379(...) MINI_PP_SEQ_SIZE_380
#define MINI_PP_SEQ_SIZE_380(...) MINI_PP_SEQ_SIZE_381
#define MINI_PP_SEQ_SIZE_381(...) MINI_PP_SEQ_SIZE_382
#define MINI_PP_SEQ_SIZE_382(...) MINI_PP_SEQ_SIZE_383
#define MINI_PP_SEQ_SIZE_383(...) MINI_PP_SEQ_SIZE_384
#define MINI_PP_SEQ_SIZE_384(...) MINI_PP_SEQ_SIZE_385
#define MINI_PP_SEQ_SIZE_385(...) MINI_PP_SEQ_SIZE_386
#define MINI_PP_SEQ_SIZE_386(...) MINI_PP_SEQ_SIZE_387
#define MINI_PP_SEQ_SIZE_387(...) MINI_PP_SEQ_SIZE_388
#define MINI_PP_SEQ_SIZE_388(...) MINI_PP_SEQ_SIZE_389
#define MINI_PP_SEQ_SIZE_389(...) MINI_PP_SEQ_SIZE_390
#define MINI_PP_SEQ_SIZE_390(...) MINI_PP_SEQ_SIZE_391
#define MINI_PP_SEQ_SIZE_391(...) MINI_PP_SEQ_SIZE_392
#define MINI_PP_SEQ_SIZE_392(...) MINI_PP_SEQ_SIZE_393
#define MINI_PP_SEQ_SIZE_393(...) MINI_PP_SEQ_SIZE_394
#define MINI_PP_SEQ_SIZE_394(...) MINI_PP_SEQ_SIZE_395
#define MINI_PP_SEQ_SIZE_395(...) MINI_PP_SEQ_SIZE_396
#define MINI_PP_SEQ_SIZE_396(...) MINI_PP_SEQ_SIZE_397
#define MINI_PP_SEQ_SIZE_397(...) MINI_PP_SEQ_SIZE_398
#define MINI_PP_SEQ_SIZE_398(...) MINI_PP_SEQ_SIZE_399
#define MINI_PP_SEQ_SIZE_399(...) MINI_PP_SEQ_SIZE_400
#define MINI_PP_SEQ_SIZE_400(...) MINI_PP_SEQ_SIZE_401
#define MINI_PP_SEQ_SIZE_401(...) MINI_PP_SEQ_SIZE_402
#define MINI_PP_SEQ_SIZE_402(...) MINI_PP_SEQ_SIZE_403
#define MINI_PP_SEQ_SIZE_403(...) MINI_PP_SEQ_SIZE_404
#define MINI_PP_SEQ_SIZE_404(...) MINI_PP_SEQ_SIZE_405
#define MINI_PP_SEQ_SIZE_405(...) MINI_PP_SEQ_SIZE_406
#define MINI_PP_SEQ_SIZE_406(...) MINI_PP_SEQ_SIZE_407
#define MINI_PP_SEQ_SIZE_407(...) MINI_PP_SEQ_SIZE_408
#define MINI_PP_SEQ_SIZE_408(...) MINI_PP_SEQ_SIZE_409
#define MINI_PP_SEQ_SIZE_409(...) MINI_PP_SEQ_SIZE_410
#define MINI_PP_SEQ_SIZE_410(...) MINI_PP_SEQ_SIZE_411
#define MINI_PP_SEQ_SIZE_411(...) MINI_PP_SEQ_SIZE_412
#define MINI_PP_SEQ_SIZE_412(...) MINI_PP_SEQ_SIZE_413
#define MINI_PP_SEQ_SIZE_413(...) MINI_PP_SEQ_SIZE_414
#define MINI_PP_SEQ_SIZE_414(...) MINI_PP_SEQ_SIZE_415
#define MINI_PP_SEQ_SIZE_415(...) MINI_PP_SEQ_SIZE_416
#define MINI_PP_SEQ_SIZE_416(...) MINI_PP_SEQ_SIZE_417
#define MINI_PP_SEQ_SIZE_417(...) MINI_PP_SEQ_SIZE_418
#define MINI_PP_SEQ_SIZE_418(...) MINI_PP_SEQ_SIZE_419
#define MINI_PP_SEQ_SIZE_419(...) MINI_PP_SEQ_SIZE_420
#define MINI_PP_SEQ_SIZE_420(...) MINI_PP_SEQ_SIZE_421
#define MINI_PP_SEQ_SIZE_421(...) MINI_PP_SEQ_SIZE_422
#define MINI_PP_SEQ_SIZE_422(...) MINI_PP_SEQ_SIZE_423
#define MINI_PP_SEQ_SIZE_423(...) MINI_PP_SEQ_SIZE_424
#define MINI_PP_SEQ_SIZE_424(...) MINI_PP_SEQ_SIZE_425
#define MINI_PP_SEQ_SIZE_425(...) MINI_PP_SEQ_SIZE_426
#define MINI_PP_SEQ_SIZE_426(...) MINI_PP_SEQ_SIZE_427
#define MINI_PP_SEQ_SIZE_427(...) MINI_PP_SEQ_SIZE_428
#define MINI_PP_SEQ_SIZE_428(...) MINI_PP_SEQ_SIZE_429
#define MINI_PP_SEQ_SIZE_429(...) MINI_PP_SEQ_SIZE_430
#define MINI_PP_SEQ_SIZE_430(...) MINI_PP_SEQ_SIZE_431
#define MINI_PP_SEQ_SIZE_431(...) MINI_PP_SEQ_SIZE_432
#define MINI_PP_SEQ_SIZE_432(...) MINI_PP_SEQ_SIZE_433
#define MINI_PP_SEQ_SIZE_433(...) MINI_PP_SEQ_SIZE_434
#define MINI_PP_SEQ_SIZE_434(...) MINI_PP_SEQ_SIZE_435
#define MINI_PP_SEQ_SIZE_435(...) MINI_PP_SEQ_SIZE_436
#define MINI_PP_SEQ_SIZE_436(...) MINI_PP_SEQ_SIZE_437
#define MINI_PP_SEQ_SIZE_437(...) MINI_PP_SEQ_SIZE_438
#define MINI_PP_SEQ_SIZE_438(...) MINI_PP_SEQ_SIZE_439
#define MINI_PP_SEQ_SIZE_439(...) MINI_PP_SEQ_SIZE_440
#define MINI_PP_SEQ_SIZE_440(...) MINI_PP_SEQ_SIZE_441
#define MINI_PP_SEQ_SIZE_441(...) MINI_PP_SEQ_SIZE_442
#define MINI_PP_SEQ_SIZE_442(...) MINI_PP_SEQ_SIZE_443
#define MINI_PP_SEQ_SIZE_443(...) MINI_PP_SEQ_SIZE_444
#define MINI_PP_SEQ_SIZE_444(...) MINI_PP_SEQ_SIZE_445
#define MINI_PP_SEQ_SIZE_445(...) MINI_PP_SEQ_SIZE_446
#define MINI_PP_SEQ_SIZE_446(...) MINI_PP_SEQ_SIZE_447
#define MINI_PP_SEQ_SIZE_447(...) MINI_PP_SEQ_SIZE_448
#define MINI_PP_SEQ_SIZE_448(...) MINI_PP_SEQ_SIZE_449
#define MINI_PP_SEQ_SIZE_449(...) MINI_PP_SEQ_SIZE_450
#define MINI_PP_SEQ_SIZE_450(...) MINI_PP_SEQ_SIZE_451
#define MINI_PP_SEQ_SIZE_451(...) MINI_PP_SEQ_SIZE_452
#define MINI_PP_SEQ_SIZE_452(...) MINI_PP_SEQ_SIZE_453
#define MINI_PP_SEQ_SIZE_453(...) MINI_PP_SEQ_SIZE_454
#define MINI_PP_SEQ_SIZE_454(...) MINI_PP_SEQ_SIZE_455
#define MINI_PP_SEQ_SIZE_455(...) MINI_PP_SEQ_SIZE_456
#define MINI_PP_SEQ_SIZE_456(...) MINI_PP_SEQ_SIZE_457
#define MINI_PP_SEQ_SIZE_457(...) MINI_PP_SEQ_SIZE_458
#define MINI_PP_SEQ_SIZE_458(...) MINI_PP_SEQ_SIZE_459
#define MINI_PP_SEQ_SIZE_459(...) MINI_PP_SEQ_SIZE_460
#define MINI_PP_SEQ_SIZE_460(...) MINI_PP_SEQ_SIZE_461
#define MINI_PP_SEQ_SIZE_461(...) MINI_PP_SEQ_SIZE_462
#define MINI_PP_SEQ_SIZE_462(...) MINI_PP_SEQ_SIZE_463
#define MINI_PP_SEQ_SIZE_463(...) MINI_PP_SEQ_SIZE_464
#define MINI_PP_SEQ_SIZE_464(...) MINI_PP_SEQ_SIZE_465
#define MINI_PP_SEQ_SIZE_465(...) MINI_PP_SEQ_SIZE_466
#define MINI_PP_SEQ_SIZE_466(...) MINI_PP_SEQ_SIZE_467
#define MINI_PP_SEQ_SIZE_467(...) MINI_PP_SEQ_SIZE_468
#define MINI_PP_SEQ_SIZE_468(...) MINI_PP_SEQ_SIZE_469
#define MINI_PP_SEQ_SIZE_469(...) MINI_PP_SEQ_SIZE_470
#define MINI_PP_SEQ_SIZE_470(...) MINI_PP_SEQ_SIZE_471
#define MINI_PP_SEQ_SIZE_471(...) MINI_PP_SEQ_SIZE_472
#define MINI_PP_SEQ_SIZE_472(...) MINI_PP_SEQ_SIZE_473
#define MINI_PP_SEQ_SIZE_473(...) MINI_PP_SEQ_SIZE_474
#define MINI_PP_SEQ_SIZE_474(...) MINI_PP_SEQ_SIZE_475
#define MINI_PP_SEQ_SIZE_475(...) MINI_PP_SEQ_SIZE_476
#define MINI_PP_SEQ_SIZE_476(...) MINI_PP_SEQ_SIZE_477
#define MINI_PP_SEQ_SIZE_477(...) MINI_PP_SEQ_SIZE_478
#define MINI_PP_SEQ_SIZE_478(...) MINI_PP_SEQ_SIZE_479
#define MINI_PP_SEQ_SIZE_479(...) MINI_PP_SEQ_SIZE_480
#define MINI_PP_SEQ_SIZE_480(...) MINI_PP_SEQ_SIZE_481
#define MINI_PP_SEQ_SIZE_481(...) MINI_PP_SEQ_SIZE_482
#define MINI_PP_SEQ_SIZE_482(...) MINI_PP_SEQ_SIZE_483
#define MINI_PP_SEQ_SIZE_483(...) MINI_PP_SEQ_SIZE_484
#define MINI_PP_SEQ_SIZE_484(...) MINI_PP_SEQ_SIZE_485
#define MINI_PP_SEQ_SIZE_485(...) MINI_PP_SEQ_SIZE_486
#define MINI_PP_SEQ_SIZE_486(...) MINI_PP_SEQ_SIZE_487
#define MINI_PP_SEQ_SIZE_487(...) MINI_PP_SEQ_SIZE_488
#define MINI_PP_SEQ_SIZE_488(...) MINI_PP_SEQ_SIZE_489
#define MINI_PP_SEQ_SIZE_489(...) MINI_PP_SEQ_SIZE_490
#define MINI_PP_SEQ_SIZE_490(...) MINI_PP_SEQ_SIZE_491
#define MINI_PP_SEQ_SIZE_491(...) MINI_PP_SEQ_SIZE_492
#define MINI_PP_SEQ_SIZE_492(...) MINI_PP_SEQ_SIZE_493
#define MINI_PP_SEQ_SIZE_493(...) MINI_PP_SEQ_SIZE_494
#define MINI_PP_SEQ_SIZE_494(...) MINI_PP_SEQ_SIZE_495
#define MINI_PP_SEQ_SIZE_495(...) MINI_PP_SEQ_SIZE_496
#define MINI_PP_SEQ_SIZE_496(...) MINI_PP_SEQ_SIZE_497
#define MINI_PP_SEQ_SIZE_497(...) MINI_PP_SEQ_SIZE_498
#define MINI_PP_SEQ_SIZE_498(...) MINI_PP_SEQ_SIZE_499
#define MINI_PP_SEQ_SIZE_499(...) MINI_PP_SEQ_SIZE_500

#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_0 0
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_1 1
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_2 2
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_3 3
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_4 4
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_5 5
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_6 6
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_7 7
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_8 8
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_9 9
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_10 10
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_11 11
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_12 12
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_13 13
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_14 14
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_15 15
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_16 16
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_17 17
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_18 18
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_19 19
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_20 20
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_21 21
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_22 22
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_23 23
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_24 24
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_25 25
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_26 26
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_27 27
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_28 28
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_29 29
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_30 30
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_31 31
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_32 32
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_33 33
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_34 34
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_35 35
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_36 36
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_37 37
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_38 38
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_39 39
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_40 40
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_41 41
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_42 42
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_43 43
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_44 44
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_45 45
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_46 46
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_47 47
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_48 48
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_49 49
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_50 50
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_51 51
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_52 52
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_53 53
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_54 54
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_55 55
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_56 56
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_57 57
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_58 58
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_59 59
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_60 60
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_61 61
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_62 62
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_63 63
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_64 64
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_65 65
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_66 66
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_67 67
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_68 68
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_69 69
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_70 70
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_71 71
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_72 72
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_73 73
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_74 74
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_75 75
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_76 76
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_77 77
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_78 78
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_79 79
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_80 80
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_81 81
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_82 82
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_83 83
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_84 84
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_85 85
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_86 86
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_87 87
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_88 88
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_89 89
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_90 90
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_91 91
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_92 92
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_93 93
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_94 94
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_95 95
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_96 96
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_97 97
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_98 98
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_99 99
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_100 100
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_101 101
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_102 102
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_103 103
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_104 104
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_105 105
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_106 106
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_107 107
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_108 108
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_109 109
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_110 110
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_111 111
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_112 112
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_113 113
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_114 114
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_115 115
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_116 116
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_117 117
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_118 118
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_119 119
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_120 120
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_121 121
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_122 122
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_123 123
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_124 124
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_125 125
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_126 126
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_127 127
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_128 128
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_129 129
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_130 130
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_131 131
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_132 132
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_133 133
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_134 134
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_135 135
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_136 136
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_137 137
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_138 138
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_139 139
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_140 140
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_141 141
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_142 142
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_143 143
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_144 144
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_145 145
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_146 146
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_147 147
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_148 148
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_149 149
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_150 150
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_151 151
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_152 152
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_153 153
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_154 154
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_155 155
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_156 156
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_157 157
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_158 158
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_159 159
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_160 160
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_161 161
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_162 162
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_163 163
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_164 164
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_165 165
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_166 166
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_167 167
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_168 168
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_169 169
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_170 170
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_171 171
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_172 172
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_173 173
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_174 174
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_175 175
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_176 176
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_177 177
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_178 178
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_179 179
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_180 180
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_181 181
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_182 182
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_183 183
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_184 184
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_185 185
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_186 186
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_187 187
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_188 188
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_189 189
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_190 190
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_191 191
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_192 192
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_193 193
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_194 194
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_195 195
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_196 196
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_197 197
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_198 198
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_199 199
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_200 200
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_201 201
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_202 202
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_203 203
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_204 204
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_205 205
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_206 206
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_207 207
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_208 208
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_209 209
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_210 210
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_211 211
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_212 212
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_213 213
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_214 214
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_215 215
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_216 216
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_217 217
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_218 218
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_219 219
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_220 220
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_221 221
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_222 222
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_223 223
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_224 224
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_225 225
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_226 226
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_227 227
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_228 228
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_229 229
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_230 230
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_231 231
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_232 232
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_233 233
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_234 234
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_235 235
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_236 236
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_237 237
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_238 238
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_239 239
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_240 240
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_241 241
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_242 242
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_243 243
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_244 244
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_245 245
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_246 246
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_247 247
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_248 248
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_249 249
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_250 250
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_251 251
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_252 252
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_253 253
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_254 254
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_255 255
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_256 256
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_257 257
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_258 258
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_259 259
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_260 260
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_261 261
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_262 262
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_263 263
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_264 264
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_265 265
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_266 266
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_267 267
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_268 268
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_269 269
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_270 270
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_271 271
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_272 272
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_273 273
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_274 274
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_275 275
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_276 276
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_277 277
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_278 278
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_279 279
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_280 280
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_281 281
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_282 282
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_283 283
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_284 284
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_285 285
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_286 286
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_287 287
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_288 288
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_289 289
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_290 290
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_291 291
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_292 292
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_293 293
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_294 294
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_295 295
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_296 296
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_297 297
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_298 298
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_299 299
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_300 300
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_301 301
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_302 302
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_303 303
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_304 304
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_305 305
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_306 306
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_307 307
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_308 308
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_309 309
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_310 310
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_311 311
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_312 312
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_313 313
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_314 314
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_315 315
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_316 316
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_317 317
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_318 318
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_319 319
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_320 320
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_321 321
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_322 322
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_323 323
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_324 324
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_325 325
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_326 326
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_327 327
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_328 328
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_329 329
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_330 330
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_331 331
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_332 332
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_333 333
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_334 334
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_335 335
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_336 336
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_337 337
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_338 338
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_339 339
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_340 340
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_341 341
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_342 342
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_343 343
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_344 344
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_345 345
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_346 346
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_347 347
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_348 348
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_349 349
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_350 350
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_351 351
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_352 352
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_353 353
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_354 354
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_355 355
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_356 356
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_357 357
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_358 358
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_359 359
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_360 360
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_361 361
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_362 362
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_363 363
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_364 364
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_365 365
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_366 366
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_367 367
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_368 368
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_369 369
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_370 370
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_371 371
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_372 372
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_373 373
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_374 374
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_375 375
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_376 376
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_377 377
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_378 378
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_379 379
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_380 380
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_381 381
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_382 382
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_383 383
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_384 384
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_385 385
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_386 386
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_387 387
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_388 388
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_389 389
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_390 390
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_391 391
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_392 392
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_393 393
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_394 394
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_395 395
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_396 396
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_397 397
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_398 398
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_399 399
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_400 400
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_401 401
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_402 402
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_403 403
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_404 404
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_405 405
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_406 406
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_407 407
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_408 408
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_409 409
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_410 410
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_411 411
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_412 412
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_413 413
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_414 414
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_415 415
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_416 416
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_417 417
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_418 418
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_419 419
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_420 420
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_421 421
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_422 422
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_423 423
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_424 424
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_425 425
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_426 426
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_427 427
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_428 428
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_429 429
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_430 430
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_431 431
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_432 432
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_433 433
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_434 434
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_435 435
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_436 436
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_437 437
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_438 438
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_439 439
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_440 440
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_441 441
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_442 442
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_443 443
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_444 444
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_445 445
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_446 446
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_447 447
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_448 448
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_449 449
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_450 450
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_451 451
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_452 452
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_453 453
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_454 454
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_455 455
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_456 456
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_457 457
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_458 458
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_459 459
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_460 460
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_461 461
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_462 462
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_463 463
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_464 464
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_465 465
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_466 466
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_467 467
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_468 468
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_469 469
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_470 470
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_471 471
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_472 472
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_473 473
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_474 474
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_475 475
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_476 476
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_477 477
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_478 478
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_479 479
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_480 480
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_481 481
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_482 482
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_483 483
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_484 484
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_485 485
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_486 486
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_487 487
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_488 488
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_489 489
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_490 490
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_491 491
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_492 492
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_493 493
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_494 494
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_495 495
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_496 496
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_497 497
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_498 498
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_499 499
#define MINI_PP_SEQ_SIZE_GET_MINI_PP_SEQ_SIZE_500 500

#define MINI_PP_SEQ_SIZE(seq) MINI_PP_PRIVATE_SEQ_SIZE_IMPL(seq)
#define MINI_PP_PRIVATE_SEQ_SIZE_IMPL(seq) MINI_PP_CAT(MINI_PP_SEQ_SIZE_GET_, MINI_PP_SEQ_SIZE_0 ## seq)

static_assert(MINI_PP_SEQ_SIZE(()) == 1, "");
static_assert(MINI_PP_SEQ_SIZE(()()) == 2, "");
static_assert(MINI_PP_SEQ_SIZE(()()()) == 3, "");
static_assert(MINI_PP_SEQ_SIZE(()()()()) == 4, "");
static_assert(MINI_PP_SEQ_SIZE(()()()()()) == 5, "");

#define MY_SEQ_100() ()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()

static_assert(MINI_PP_SEQ_SIZE(MY_SEQ_100()) == 100, "");
static_assert(MINI_PP_SEQ_SIZE(MY_SEQ_100()MY_SEQ_100()) == 200, "");
static_assert(MINI_PP_SEQ_SIZE(MY_SEQ_100()MY_SEQ_100()MY_SEQ_100()) == 300, "");
static_assert(MINI_PP_SEQ_SIZE(MY_SEQ_100()MY_SEQ_100()MY_SEQ_100()MY_SEQ_100()) == 400, "");
static_assert(MINI_PP_SEQ_SIZE(MY_SEQ_100()MY_SEQ_100()MY_SEQ_100()MY_SEQ_100()MY_SEQ_100()) == 500, "");


#if 0
#define MY_INNDER_DO(x) + x
#define MY_INNER() MINI_PP_FOR_EACH(MY_INNDER_DO, 124, 123, 122, 121, \
    120, 119, 118, 117, 116, 115, 114, 113, 112, 111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100,  99,  98,  97,  96,  95,  94,  93,  92,  91, \
     90,  89,  88,  87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,  74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,  61, \
     60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,  48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,  35,  34,  33,  32,  31, \
     30,  29,  28,  27,  26,  25,  24,  23,  22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,   9,   8,   7,   6,   5,   4,   3,   2,   1)
static_assert(0 MY_INNER() == 125 * 62, "");
#endif

#if 0
#define MY_OUTER_DO(x) MY_INNER()
#define MY_OUTER() MINI_PP_FOR_EACH(MY_OUTER_DO, 1, 2, 3)
static_assert(0 MY_OUTER() == 3 * 6 * 11, "");

#define MY_OUTER2_DO(x) MY_OUTER()
#define MY_OUTER2() MINI_PP_FOR_EACH(MY_OUTER2_DO, 1, 2, 3, 4, 5)
static_assert(0 MY_OUTER2() == 5 * 3 * 6 * 11, "");
#endif

#define MINI_PP_EAT(a)

#define MINI_PP_EXPAND_4_TIMES(x) MINI_PP_EXPAND_4_TIMES_IMPL(x)
#define MINI_PP_EXPAND_4_TIMES_IMPL(x) MINI_PP_EXPAND_4_TIMES_IMPL_IMPL(x)
#define MINI_PP_EXPAND_4_TIMES_IMPL_IMPL(x) MINI_PP_EXPAND_4_TIMES_IMPL_IMPL_IMPL(x)
#define MINI_PP_EXPAND_4_TIMES_IMPL_IMPL_IMPL(x) x

#define MINI_PP_HIDE_RECURSION

#ifdef _MSC_VER
#define MINI_PP_EXPAND_16_TIMES(...) MINI_PP_EXPAND_4_TIMES(MINI_PP_EXPAND_4_TIMES(MINI_PP_EXPAND_4_TIMES(MINI_PP_EXPAND_4_TIMES(MINI_PP_EXPAND_3_TIMES(__VA_ARGS__)))))
#define MINI_PP_EXPAND_64_TIMES(...) MINI_PP_EXPAND_16_TIMES(MINI_PP_EXPAND_16_TIMES(MINI_PP_EXPAND_16_TIMES(MINI_PP_EXPAND_16_TIMES(MINI_PP_EXPAND_3_TIMES(__VA_ARGS__)))))
#define MINI_PP_EXPAND_256_TIMES(...) MINI_PP_EXPAND_64_TIMES(MINI_PP_EXPAND_64_TIMES(MINI_PP_EXPAND_64_TIMES(MINI_PP_EXPAND_64_TIMES(MINI_PP_EXPAND_3_TIMES(__VA_ARGS__)))))
#define MINI_PP_EXPAND_1024_TIMES(...) MINI_PP_EXPAND_256_TIMES(MINI_PP_EXPAND_256_TIMES(MINI_PP_EXPAND_256_TIMES(MINI_PP_EXPAND_256_TIMES(MINI_PP_EXPAND_3_TIMES(__VA_ARGS__)))))

#define MINI_PP_EXPAND_FOR_RECURSE_16_TIMES(...) MINI_PP_EXPAND_4_TIMES(MINI_PP_EXPAND_4_TIMES(MINI_PP_EXPAND_4_TIMES(MINI_PP_EXPAND_4_TIMES(MINI_PP_EXPAND_3_TIMES(__VA_ARGS__)))))
#define MINI_PP_EXPAND_FOR_RECURSE_64_TIMES(...) MINI_PP_EXPAND_FOR_RECURSE_16_TIMES(MINI_PP_EXPAND_FOR_RECURSE_16_TIMES(MINI_PP_EXPAND_FOR_RECURSE_16_TIMES(MINI_PP_EXPAND_FOR_RECURSE_16_TIMES(MINI_PP_EXPAND_3_TIMES(__VA_ARGS__)))))
#define MINI_PP_EXPAND_FOR_RECURSE_256_TIMES(...) MINI_PP_EXPAND_FOR_RECURSE_64_TIMES(MINI_PP_EXPAND_FOR_RECURSE_64_TIMES(MINI_PP_EXPAND_FOR_RECURSE_64_TIMES(MINI_PP_EXPAND_FOR_RECURSE_64_TIMES(MINI_PP_EXPAND_3_TIMES(__VA_ARGS__)))))
#define MINI_PP_EXPAND_FOR_RECURSE_1024_TIMES(...) MINI_PP_EXPAND_FOR_RECURSE_256_TIMES(MINI_PP_EXPAND_FOR_RECURSE_256_TIMES(MINI_PP_EXPAND_FOR_RECURSE_256_TIMES(MINI_PP_EXPAND_FOR_RECURSE_256_TIMES(MINI_PP_EXPAND_3_TIMES(__VA_ARGS__)))))
#else
#define MINI_PP_EXPAND_16_TIMES(...) MINI_PP_EXPAND_4_TIMES(MINI_PP_EXPAND_4_TIMES(MINI_PP_EXPAND_4_TIMES(MINI_PP_EXPAND_3_TIMES(__VA_ARGS__))))
#define MINI_PP_EXPAND_64_TIMES(...) MINI_PP_EXPAND_16_TIMES(MINI_PP_EXPAND_16_TIMES(MINI_PP_EXPAND_16_TIMES(MINI_PP_EXPAND_4_TIMES(MINI_PP_EXPAND_4_TIMES(MINI_PP_EXPAND_4_TIMES(MINI_PP_EXPAND_3_TIMES(__VA_ARGS__)))))))
#define MINI_PP_EXPAND_256_TIMES(...) MINI_PP_EXPAND_64_TIMES(MINI_PP_EXPAND_64_TIMES(MINI_PP_EXPAND_64_TIMES(MINI_PP_EXPAND_16_TIMES(MINI_PP_EXPAND_16_TIMES(MINI_PP_EXPAND_16_TIMES(MINI_PP_EXPAND_4_TIMES(MINI_PP_EXPAND_4_TIMES(MINI_PP_EXPAND_4_TIMES(MINI_PP_EXPAND_3_TIMES(__VA_ARGS__))))))))))
#define MINI_PP_EXPAND_1024_TIMES(...) MINI_PP_EXPAND_256_TIMES(MINI_PP_EXPAND_256_TIMES(MINI_PP_EXPAND_256_TIMES( MINI_PP_EXPAND_64_TIMES(MINI_PP_EXPAND_64_TIMES(MINI_PP_EXPAND_64_TIMES(MINI_PP_EXPAND_16_TIMES(MINI_PP_EXPAND_16_TIMES(MINI_PP_EXPAND_16_TIMES(MINI_PP_EXPAND_4_TIMES(MINI_PP_EXPAND_4_TIMES(MINI_PP_EXPAND_4_TIMES(MINI_PP_EXPAND_3_TIMES(__VA_ARGS__)))))))))))))

#define MINI_PP_EXPAND_FOR_RECURSE_16_TIMES(...) MINI_PP_EXPAND_4_TIMES(MINI_PP_EXPAND_4_TIMES(MINI_PP_EXPAND_4_TIMES(MINI_PP_EXPAND_2_TIMES(__VA_ARGS__))))
#define MINI_PP_EXPAND_FOR_RECURSE_64_TIMES(...) MINI_PP_EXPAND_FOR_RECURSE_16_TIMES(MINI_PP_EXPAND_FOR_RECURSE_16_TIMES(MINI_PP_EXPAND_FOR_RECURSE_16_TIMES(MINI_PP_EXPAND_FOR_RECURSE_16_TIMES(MINI_PP_EXPAND_2_TIMES(__VA_ARGS__)))))
#endif

#define TEST_REC() a TEST_REC_IMPL MINI_PP_HIDE_RECURSION ()
#define TEST_REC_IMPL()  a TEST_REC MINI_PP_HIDE_RECURSION ()

static_assert(stringsEqual(MINI_PP_TO_TEXT(MINI_PP_EXPAND_FOR_RECURSE_16_TIMES(TEST_REC())), "a a a a a a a a a a a a a a a a TEST_REC  ()"), "MINI_PP_EXPAND_FOR_RECURSE_16_TIMES is broken");
static_assert(stringsEqual(MINI_PP_TO_TEXT(MINI_PP_EXPAND_FOR_RECURSE_64_TIMES(TEST_REC())),
						   "a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a "
						   "TEST_REC  ()"), "MINI_PP_EXPAND_FOR_RECURSE_64_TIMES is broken");

static_assert(stringsEqual(MINI_PP_TO_TEXT(MINI_PP_EXPAND_FOR_RECURSE_256_TIMES(TEST_REC())),
						   "a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a "
						   "a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a "
						   "a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a "
						   "a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a "
						   "TEST_REC  ()"), "MINI_PP_EXPAND_FOR_RECURSE_256_TIMES is broken");

static_assert(stringsEqual(MINI_PP_TO_TEXT(MINI_PP_EXPAND_FOR_RECURSE_1024_TIMES(TEST_REC())),
						   "a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a "
						   "a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a "
						   "a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a "
						   "a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a "
						   "a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a "
						   "a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a "
						   "a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a "
						   "a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a "
						   "a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a "
						   "a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a "
						   "a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a "
						   "a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a "
						   "a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a "
						   "a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a "
						   "a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a "
						   "a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a "
						   "TEST_REC  ()"), "MINI_PP_EXPAND_FOR_RECURSE_1024_TIMES is broken");


#define MINI_PP_TO_SEQ(...) MINI_PP_EXPAND_FOR_RECURSE_256_TIMES(MINI_PP_PRIVATE_TO_SEQ_IMPL(__VA_ARGS__))
#define MINI_PP_PRIVATE_TO_SEQ_IMPL(...) MINI_PP_CAT_3(MINI_PP_PRIVATE_TO_SEQ_IMPL_, MINI_PP_IS_EMPTY(__VA_ARGS__), MINI_PP_IS_EQUAL(MINI_PP_NB_ARGS(__VA_ARGS__), 1)) MINI_PP_HIDE_RECURSION (__VA_ARGS__)
#define MINI_PP_PRIVATE_TO_SEQ_IMPL_10()
#define MINI_PP_PRIVATE_TO_SEQ_IMPL_01(first) (first)
#define MINI_PP_PRIVATE_TO_SEQ_IMPL_00(first, ...) (first)MINI_PP_PRIVATE_TO_SEQ_IMPL MINI_PP_HIDE_RECURSION (__VA_ARGS__)


static_assert(stringsEqual(MINI_PP_TO_TEXT(MINI_PP_TO_SEQ(a)), "(a)"), "MINI_PP_TO_SEQ is broken");
static_assert(stringsEqual(MINI_PP_TO_TEXT(MINI_PP_TO_SEQ(a, b)), "(a)(b)"), "MINI_PP_TO_SEQ is broken");
static_assert(stringsEqual(MINI_PP_TO_TEXT(MINI_PP_TO_SEQ(a, b, c)), "(a)(b)(c)"), "MINI_PP_TO_SEQ is broken");
static_assert(stringsEqual(MINI_PP_TO_TEXT(MINI_PP_TO_SEQ(
	1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125)),
	"(1)(2)(3)(4)(5)(6)(7)(8)(9)(10)(11)(12)(13)(14)(15)(16)(17)(18)(19)(20)(21)(22)(23)(24)(25)(26)(27)(28)(29)(30)(31)(32)(33)(34)(35)(36)(37)(38)(39)(40)(41)(42)(43)(44)(45)(46)(47)(48)(49)(50)(51)(52)(53)(54)(55)(56)(57)(58)(59)(60)(61)(62)(63)(64)(65)(66)(67)(68)(69)(70)(71)(72)(73)(74)(75)(76)(77)(78)(79)(80)(81)(82)(83)(84)(85)(86)(87)(88)(89)(90)(91)(92)(93)(94)(95)(96)(97)(98)(99)(100)(101)(102)(103)(104)(105)(106)(107)(108)(109)(110)(111)(112)(113)(114)(115)(116)(117)(118)(119)(120)(121)(122)(123)(124)(125)"), "MINI_PP_TO_SEQ is broken");


#define MINI_PP2_SEQ_SIZE(s)

#define MINI_PP2_PRIVATE_SEQ_SIZE_IMPL(s)


#define MINI_PP_SEQ_FOR_EACH(f, s) MINI_PP_EXPAND_FOR_RECURSE_1024_TIMES(MINI_PP_PRIVATE_SEQ_FOR_EACH_IMPL(f, s))
#define MINI_PP_PRIVATE_SEQ_FOR_EACH_IMPL(f, s) MINI_PP_CAT(MINI_PP_PRIVATE_SEQ_FOR_EACH_IMPL_, MINI_PP_IS_EMPTY(s)) MINI_PP_HIDE_RECURSION (f, s)
#define MINI_PP_PRIVATE_SEQ_FOR_EACH_IMPL_CALL(e) f(e)
#define MINI_PP_PRIVATE_SEQ_FOR_EACH_IMPL_1(f, s) s
#define MINI_PP_PRIVATE_SEQ_FOR_EACH_IMPL_0(f, s) MINI_PP_PRIVATE_SEQ_FOR_EACH_IMPL_CALL MINI_PP_PRIVATE_SEQ_FOR_EACH_IMPL MINI_PP_HIDE_RECURSION (f, s)

#if 0

#define A(x) x B MINI_PP_HIDE_RECURSION (x)
#define B(x) x A MINI_PP_HIDE_RECURSION (x)

A(foo)
MINI_PP_EXPAND(A(foo))
MINI_PP_EXPAND_2_TIMES(A(foo))
MINI_PP_EXPAND_3_TIMES(A(foo))
MINI_PP_EXPAND_4_TIMES(A(foo))
MINI_PP_DUPLICATE_4(A(foo))
MINI_PP_EXPAND_2_TIMES(A(foo))
MINI_PP_EXPAND_2_TIMES(MINI_PP_EXPAND_2_TIMES(A(foo)))
MINI_PP_EXPAND_2_TIMES(MINI_PP_EXPAND_2_TIMES(MINI_PP_EXPAND_2_TIMES(A(foo))))
MINI_PP_EXPAND_2_TIMES(MINI_PP_EXPAND_2_TIMES(MINI_PP_EXPAND_2_TIMES(MINI_PP_EXPAND_2_TIMES(A(foo)))))

#endif
