name: ci

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:        
        os:
          - windows-2022
          - ubuntu-22.04
          - macos-12
        generator:
          - "Ninja Multi-Config"
        compiler:
          - llvm-15.0.2
          - gcc-11
        build_type:
          - Debug
          - Release
        include:
          - os: windows-2022
            generator: "Visual Studio 17 2022"
            compiler: msvc-17.0
            build_type: Debug
            
          - os: windows-2022
            generator: "Visual Studio 17 2022"
            compiler: msvc-17.0
            build_type: Release

          - os: windows-2019
            generator: "Visual Studio 16 2019"
            compiler: msvc-16.0
            build_type: Debug
            
          - os: windows-2019
            generator: "Visual Studio 16 2019"
            compiler: msvc-16.0
            build_type: Release
            
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Cpp
      uses: aminya/setup-cpp@v1
      with:
          compiler: ${{ matrix.compiler }}
          vcvarsall: ${{ contains(matrix.os, 'windows') }}
          cmake: true
          ninja: true

    - name: Configure
      run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -G "${{matrix.generator}}" -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

    - name: Test FetchContent Interface
      run: |
        cmake -S ${{github.workspace}}/tests/fetchcontent  -B ${{github.workspace}}/tests/fetchcontent/build -G "${{matrix.generator}}" -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DMINI_PP_WANTED_SHA=$env:GITHUB_SHA
        cmake  --build ${{github.workspace}}/tests/fetchcontent/build --config ${{matrix.build_type}}

    - name: Test Install Interface
      run: |
        cmake --install ${{github.workspace}}/build --config ${{matrix.build_type}}
        cmake -S ${{github.workspace}}/tests/install  -B ${{github.workspace}}/tests/install/build -G "${{matrix.generator}}" -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_PREFIX_PATH=${{github.workspace}}/install
        cmake  --build ${{github.workspace}}/tests/install/build --config ${{matrix.build_type}}
